# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ZSWKWebViewVC-master' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
   pod 'WebViewJavascriptBridge'
  # Pods for ZSWKWebViewVC-master

end
